{% set name = "yaqc-bluesky" %}
{% set version = "2022.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 449e75dd52ea5cc23625c58ab6107c7e1b1b5f5038f46f0a96e8d7ddf9cd57d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - bluesky >=1.6.6
    - happi >=1.9.0
    - yaqc >=2021.10.0
    - python >=3.8
  run:
    - bluesky >=1.6.6
    - happi >=1.9.0
    - yaqc >=2021.10.0
    - python >=3.8
  run_constrained:
    - databroker >=1.2.2

test:
  imports:
    - yaqc_bluesky
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/yaqc-bluesky
  summary: A bluesky interface to the yaq instrument control framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
