{% set name = "yaqc-bluesky" %}
{% set version = "2022.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4aef5355b99fd9d3e931859744fbce9602c525bd6d234b2226bc06e7dca6660

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - bluesky
    - happi
    - yaqc >=2020.10.0
    - python >=3.8
  run:
    - bluesky
    - happi
    - yaqc >=2020.10.0
    - python >=3.8
  run_constrained:
    - databroker >=1.2.2

test:
  imports:
    - yaqc_bluesky
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/yaqc-bluesky
  summary: A bluesky interface to the yaq instrument control framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
